theme: jekyll-theme-hacker

# Site settings
title: ClaudeMao's Blog                    #你博客的标题
SEOTitle: CCCCClaudeMao        #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
email: ClaudeMao0131@gmail.com    
description: "A graceful personal blog"              #网站介绍
keyword: "ClaudeMao" #关键词
url: "https://ClaudeMao.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "被生活叫醒的人"
sidebar-avatar:C:/Users/98415/Desktop/Germany.jpg      # 你的个人头像
